version: '2'
services:
  nginx:
    image: nginx:1.11-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php
  php:
    #image: f05b0ae99187
    image: chuajose/php74
    ports:
      - "2323:22"
    volumes:
      - ./etc/dev/nginx/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - .:/app
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports:
      - 5601:5601
    volumes:
      - "$PWD/etc/dev/kibana/config.7.4:/usr/share/kibana/config/kibana.yml"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    ulimits:
              nofile:
                  soft: 65536
                  hard: 65536
              memlock:
                  soft: -1
                  hard: -1
    ports:
      - "9200:9200"
