<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerITT8F5F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerITT8F5F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerITT8F5F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerITT8F5F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerITT8F5F\App_KernelDevDebugContainer([
    'container.build_hash' => 'ITT8F5F',
    'container.build_id' => '0fb36dd5',
    'container.build_time' => 1597855245,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerITT8F5F');
